apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: spacechatdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: spacechatdb/frontend:latest
          env:
            - name: ORIGIN
              value: http://frontend.spacechatdb.svc
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: spacechatdb
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
